<?php

namespace Database\Seeders;

use App\Models\Tour;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TourSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the tours table.
     */
    public function run(): void
    {
        $tours = [
            [
                'title' => 'Tour Hà Nội - Hạ Long',
                'description' => 'Khám phá vẻ đẹp của thủ đô Hà Nội và vịnh Hạ Long tuyệt vời với những hang động kỳ bí.',
                'price' => 2500000,
                'duration' => 3,
                'location' => 'Hà Nội - Hạ Long',
                'start_date' => '2026-05-01',
                'end_date' => '2026-05-03',
                'slots' => 30,
                'available_slots' => 0,
                'image' => 'tours/ha-long.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Đà Nẵng - Hội An',
                'description' => 'Tận hưởng bãi biển Đà Nẵng nổi tiếng và phố cổ Hội An với kiến trúc độc đáo.',
                'price' => 1800000,
                'duration' => 2,
                'location' => 'Đà Nẵng - Hội An',
                'start_date' => '2026-05-05',
                'end_date' => '2026-05-06',
                'slots' => 25,
                'available_slots' => 22,
                'image' => 'tours/da-nang.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour TP.HCM - Mekong',
                'description' => 'Khám phá sản sắc của thành phố Hồ Chí Minh và du ngoạn sông Mekong thú vị.',
                'price' => 2200000,
                'duration' => 3,
                'location' => 'TP.HCM - Đồng Tháp',
                'start_date' => '2026-05-10',
                'end_date' => '2026-05-12',
                'slots' => 35,
                'available_slots' => 10,
                'image' => 'tours/mekong.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Sa Pa - Fansipan',
                'description' => 'Trải nghiệm núi Fansipan hùng vĩ và vẻ đẹp thiên nhiên của Sa Pa.',
                'price' => 3000000,
                'duration' => 4,
                'location' => 'Sa Pa - Fansipan',
                'start_date' => '2026-05-15',
                'end_date' => '2026-05-18',
                'slots' => 20,
                'available_slots' => 20,
                'image' => 'tours/sapa.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Nha Trang - Vinpearl',
                'description' => 'Tắm biển ở Nha Trang đẹp như tranh và vui chơi tại đảo Vinpearl.',
                'price' => 1500000,
                'duration' => 2,
                'location' => 'Nha Trang',
                'start_date' => '2026-05-20',
                'end_date' => '2026-05-21',
                'slots' => 40,
                'available_slots' => 22,
                'image' => 'tours/nha-trang.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Đà Lạt - Thác Pongour',
                'description' => 'Khám phá thành phố ngàn hoa Đà Lạt và những thác nước đẹp mê hồn.',
                'price' => 1700000,
                'duration' => 2,
                'location' => 'Đà Lạt',
                'start_date' => '2026-05-25',
                'end_date' => '2026-05-26',
                'slots' => 30,
                'available_slots' => 19,
                'image' => 'tours/da-lat.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Phú Quốc - Thiên đường biển',
                'description' => 'Đảo Phú Quốc với bãi biển trắng, nước xanh trong vắt và hải sản tươi ngon.',
                'price' => 2800000,
                'duration' => 3,
                'location' => 'Phú Quốc',
                'start_date' => '2026-06-01',
                'end_date' => '2026-06-03',
                'slots' => 28,
                'available_slots' => 11,
                'image' => 'tours/phu-quoc.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Huế - Đại Nội',
                'description' => 'Tìm hiểu lịch sử vương triều Nguyễn tại kinh thành Huế cổ kính.',
                'price' => 1400000,
                'duration' => 2,
                'location' => 'Huế',
                'start_date' => '2026-06-05',
                'end_date' => '2026-06-06',
                'slots' => 25,
                'available_slots' => 25,
                'image' => 'tours/hue.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Cát Bà - Lan Hạ',
                'description' => 'Khám phá vẻ đẹp hoang sơ của đảo Cát Bà và vịnh Lan Hạ tuyệt mỹ.',
                'price' => 2100000,
                'duration' => 3,
                'location' => 'Cát Bà',
                'start_date' => '2026-06-10',
                'end_date' => '2026-06-12',
                'slots' => 22,
                'available_slots' => 8,
                'image' => 'tours/cat-ba.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Hà Giang - Lũng Cú',
                'description' => 'Chinh phục đỉnh Lũng Cú - điểm cực bắc của Việt Nam với cảnh quan kỳ thú.',
                'price' => 3500000,
                'duration' => 5,
                'location' => 'Hà Giang',
                'start_date' => '2026-06-15',
                'end_date' => '2026-06-19',
                'slots' => 15,
                'available_slots' => 9,
                'image' => 'tours/ha-giang.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Sơn Trà - Hải Vân',
                'description' => 'Trải nghiệm đèo Hải Vân hùng vĩ và vẻ đẹp hoang sơ của bán đảo Sơn Trà.',
                'price' => 1600000,
                'duration' => 2,
                'location' => 'Đà Nẵng - Huế',
                'start_date' => '2026-06-20',
                'end_date' => '2026-06-21',
                'slots' => 32,
                'available_slots' => 1,
                'image' => 'tours/son-tra.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Côn Đảo - Phú Hài',
                'description' => 'Đảo Côn Đảo với những bãi biển hoang dã, lịch sử và văn hóa độc đáo.',
                'price' => 3200000,
                'duration' => 3,
                'location' => 'Côn Đảo',
                'start_date' => '2026-06-25',
                'end_date' => '2026-06-27',
                'slots' => 18,
                'available_slots' => 2,
                'image' => 'tours/con-dao.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Vạn Hạ - Hồ Duyên Hải',
                'description' => 'Khám phá hồ Duyên Hải xinh đẹp và vẻ đẹp tự nhiên của vùng Vạn Hạ.',
                'price' => 1300000,
                'duration' => 1,
                'location' => 'Quảng Ninh',
                'start_date' => '2026-07-01',
                'end_date' => '2026-07-01',
                'slots' => 35,
                'available_slots' => 2,
                'image' => 'tours/van-ha.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Mai Châu - Mộc Châu',
                'description' => 'Thung lũng Mai Châu yên bình với bản làng Tây Bộ và cao nguyên Mộc Châu xanh mát.',
                'price' => 1900000,
                'duration' => 2,
                'location' => 'Hòa Bình - Sơn La',
                'start_date' => '2026-07-05',
                'end_date' => '2026-07-06',
                'slots' => 26,
                'available_slots' => 2,
                'image' => 'tours/mai-chau.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Tuyên Quang - Thác Ba Bể',
                'description' => 'Hồ Ba Bể huyền bí với những thác nước tuyệt đẹp giữa núi rừng Tuyên Quang.',
                'price' => 2000000,
                'duration' => 3,
                'location' => 'Tuyên Quang',
                'start_date' => '2026-07-10',
                'end_date' => '2026-07-12',
                'slots' => 24,
                'available_slots' => 1,
                'image' => 'tours/ba-be.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Ninh Bình - Tràng An',
                'description' => 'Khám phá vẻ đẹp tuyệt mỹ của Tràng An với những hang động và thuyền kayak.',
                'price' => 1550000,
                'duration' => 2,
                'location' => 'Ninh Bình',
                'start_date' => '2026-07-15',
                'end_date' => '2026-07-16',
                'slots' => 28,
                'available_slots' => 14,
                'image' => 'tours/ninh-binh.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Hạ Giang - Đông Hải',
                'description' => 'Vẻ đẹp hoang sơ của vịnh Hạ Giang với những hòn đảo kỳ vĩ và nước biển trong xanh.',
                'price' => 2300000,
                'duration' => 3,
                'location' => 'Hạ Giang',
                'start_date' => '2026-07-20',
                'end_date' => '2026-07-22',
                'slots' => 32,
                'available_slots' => 16,
                'image' => 'tours/ha-giang-2.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Quảng Bình - Phong Nha',
                'description' => 'Hang Phong Nha hùng vĩ và vẻ đẹp kỳ thú của vương quốc những hang động.',
                'price' => 1750000,
                'duration' => 2,
                'location' => 'Quảng Bình',
                'start_date' => '2026-07-25',
                'end_date' => '2026-07-26',
                'slots' => 20,
                'available_slots' => 20,
                'image' => 'tours/phong-nha.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Lạng Sơn - Thác Bản Giốc',
                'description' => 'Khám phá thác Bản Giốc hùng vĩ trên biên giới Việt - Trung.',
                'price' => 1650000,
                'duration' => 2,
                'location' => 'Lạng Sơn',
                'start_date' => '2026-08-01',
                'end_date' => '2026-08-02',
                'slots' => 18,
                'available_slots' => 9,
                'image' => 'tours/ban-gioc.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Yên Bái - Sapa',
                'description' => 'Trekking tại Sapa với những cảnh đẹp núi rừng và người dân tộc Hà Nhì.',
                'price' => 2650000,
                'duration' => 3,
                'location' => 'Yên Bái - Sa Pa',
                'start_date' => '2026-08-05',
                'end_date' => '2026-08-07',
                'slots' => 16,
                'available_slots' => 16,
                'image' => 'tours/yenbai.jpg',
                'status' => 'inactive',
            ],
        ];

        foreach ($tours as $tour) {
            Tour::create($tour);
        }
    }
}
