<?php

namespace Database\Seeders;

use App\Models\Tour;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TourSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $tours = [
            [
                'title' => 'Tour Quy Nhơn - Kỳ Co Eo Gió',
                'description' => 'Khám phá bãi biển Kỳ Co trong vắt và ngắm hoàng hôn tuyệt đẹp tại Eo Gió.',
                'price' => 2400000,
                'duration' => 3,
                'location' => 'Bình Định',
                'start_date' => '2026-08-10',
                'end_date' => '2026-08-12',
                'slots' => 30,
                'available_slots' => 25,
                'image' => 'tours/ha-long.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Tuy Hòa - Tháp Nghinh Phong',
                'description' => 'Check-in tháp Nghinh Phong biểu tượng và ngắm kiến trúc độc đáo xứ hoa vàng cỏ xanh.',
                'price' => 1950000,
                'duration' => 2,
                'location' => 'Phú Yên',
                'start_date' => '2026-08-15',
                'end_date' => '2026-08-16',
                'slots' => 25,
                'available_slots' => 20,
                'image' => 'tours/da-nang.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Cần Thơ - Chợ Nổi Cái Răng',
                'description' => 'Trải nghiệm nét văn hóa sông nước đặc sắc tại chợ nổi lớn nhất miền Tây.',
                'price' => 1350000,
                'duration' => 2,
                'location' => 'Cần Thơ',
                'start_date' => '2026-08-20',
                'end_date' => '2026-08-21',
                'slots' => 40,
                'available_slots' => 38,
                'image' => 'tours/mekong.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Mù Cang Chải - Ruộng Bậc Thang',
                'description' => 'Ngắm mùa vàng rực rỡ trên những thửa ruộng bậc thang hùng vĩ vùng Tây Bắc.',
                'price' => 2200000,
                'duration' => 3,
                'location' => 'Yên Bái',
                'start_date' => '2026-08-25',
                'end_date' => '2026-08-27',
                'slots' => 20,
                'available_slots' => 0,
                'image' => 'tours/sapa.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Phan Thiết - Mũi Né',
                'description' => 'Trải nghiệm trượt cát vui nhộn và nghỉ dưỡng tại thiên đường resort biển.',
                'price' => 1650000,
                'duration' => 2,
                'location' => 'Bình Thuận',
                'start_date' => '2026-09-01',
                'end_date' => '2026-09-02',
                'slots' => 35,
                'available_slots' => 30,
                'image' => 'tours/nha-trang.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Bảo Lộc - Thác Đambri',
                'description' => 'Hòa mình vào thiên nhiên cao nguyên tươi mát và dòng thác đổ kỳ vĩ.',
                'price' => 1450000,
                'duration' => 2,
                'location' => 'Lâm Đồng',
                'start_date' => '2026-09-05',
                'end_date' => '2026-09-06',
                'slots' => 30,
                'available_slots' => 30,
                'image' => 'tours/da-lat.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Đảo Nam Du - Biển Đảo Hoang Sơ',
                'description' => 'Lặn ngắm san hô tại hòn đảo xinh đẹp hoang sơ giữa trùng khơi mây nước.',
                'price' => 2600000,
                'duration' => 3,
                'location' => 'Kiên Giang',
                'start_date' => '2026-09-10',
                'end_date' => '2026-09-12',
                'slots' => 25,
                'available_slots' => 12,
                'image' => 'tours/phu-quoc.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Quảng Trị - Thành Cổ Lịch Sử',
                'description' => 'Hành trình tâm linh về lại vĩ tuyến 17 và Thành cổ Quảng Trị oai hùng.',
                'price' => 1500000,
                'duration' => 2,
                'location' => 'Quảng Trị',
                'start_date' => '2026-09-15',
                'end_date' => '2026-09-16',
                'slots' => 20,
                'available_slots' => 20,
                'image' => 'tours/hue.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Đảo Cô Tô - Biển Xanh Cát Trắng',
                'description' => 'Khám phá thiên đường biển đảo miền Bắc với dòng nước trong xanh như ngọc.',
                'price' => 2350000,
                'duration' => 3,
                'location' => 'Quảng Ninh',
                'start_date' => '2026-09-20',
                'end_date' => '2026-09-22',
                'slots' => 24,
                'available_slots' => 15,
                'image' => 'tours/cat-ba.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Đồng Văn - Mã Pí Lèng',
                'description' => 'Chinh phục một trong tứ đại đỉnh đèo và ngắm nhìn dòng sông Nho Quế xanh mướt.',
                'price' => 3200000,
                'duration' => 4,
                'location' => 'Hà Giang',
                'start_date' => '2026-09-25',
                'end_date' => '2026-09-28',
                'slots' => 15,
                'available_slots' => 5,
                'image' => 'tours/ha-giang.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Lý Sơn - Vương Quốc Tỏi',
                'description' => 'Hành trình khám phá miệng núi lửa cổ đại và biển đảo Lý Sơn tuyệt mỹ.',
                'price' => 2700000,
                'duration' => 3,
                'location' => 'Quảng Ngãi',
                'start_date' => '2026-10-01',
                'end_date' => '2026-10-03',
                'slots' => 20,
                'available_slots' => 0,
                'image' => 'tours/son-tra.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Vũng Tàu - Biển Xanh Nắng Vàng',
                'description' => 'Nghỉ dưỡng cuối tuần tại thành phố biển Vũng Tàu sôi động và đầy nắng.',
                'price' => 1200000,
                'duration' => 2,
                'location' => 'Bà Rịa - Vũng Tàu',
                'start_date' => '2026-10-05',
                'end_date' => '2026-10-06',
                'slots' => 45,
                'available_slots' => 0,
                'image' => 'tours/con-dao.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Trà Cổ - Móng Cái',
                'description' => 'Ghé thăm bãi biển Trà Cổ - nơi đặt nét bút đầu tiên trên bản đồ hình chữ S.',
                'price' => 1800000,
                'duration' => 2,
                'location' => 'Quảng Ninh',
                'start_date' => '2026-10-10',
                'end_date' => '2026-10-11',
                'slots' => 30,
                'available_slots' => 14,
                'image' => 'tours/van-ha.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Bắc Hà - Chợ Phiên Vùng Cao',
                'description' => 'Khám phá sắc màu văn hóa rực rỡ tại phiên chợ vùng cao vùng Tây Bắc.',
                'price' => 1900000,
                'duration' => 2,
                'location' => 'Lào Cai',
                'start_date' => '2026-10-15',
                'end_date' => '2026-10-16',
                'slots' => 22,
                'available_slots' => 2,
                'image' => 'tours/mai-chau.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Cao Bằng - Động Ngườm Ngao',
                'description' => 'Chiêm ngưỡng kiệt tác thạch nhũ huyền ảo bên trong hang động kỳ vĩ.',
                'price' => 2300000,
                'duration' => 3,
                'location' => 'Cao Bằng',
                'start_date' => '2026-10-20',
                'end_date' => '2026-10-22',
                'slots' => 18,
                'available_slots' => 4,
                'image' => 'tours/ba-be.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Tam Cốc - Bích Động',
                'description' => 'Du thuyền trên dòng sông Ngô Đồng ngắm đồng lúa chín vàng thơ mộng.',
                'price' => 1400000,
                'duration' => 2,
                'location' => 'Ninh Bình',
                'start_date' => '2026-10-25',
                'end_date' => '2026-10-26',
                'slots' => 30,
                'available_slots' => 12,
                'image' => 'tours/ninh-binh.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Du Thuyền Vịnh Hạ Long',
                'description' => 'Trải nghiệm ngủ đêm đẳng cấp trên du thuyền sang trọng giữa lòng di sản.',
                'price' => 3800000,
                'duration' => 2,
                'location' => 'Quảng Ninh',
                'start_date' => '2026-11-01',
                'end_date' => '2026-11-02',
                'slots' => 20,
                'available_slots' => 10,
                'image' => 'tours/ha-giang-2.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Hang Én - Khám Phá Kỳ Quan',
                'description' => 'Hành trình trekking mạo hiểm vào sâu bên trong hang én lớn thứ ba thế giới.',
                'price' => 4500000,
                'duration' => 3,
                'location' => 'Quảng Bình',
                'start_date' => '2026-11-05',
                'end_date' => '2026-11-07',
                'slots' => 12,
                'available_slots' => 12,
                'image' => 'tours/phong-nha.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Lạng Sơn - Mẫu Sơn Tuyết Phủ',
                'description' => 'Săn mây mây gió ngút ngàn và trải nghiệm nét văn hóa Dao đặc sắc trên đỉnh Mẫu Sơn.',
                'price' => 1700000,
                'duration' => 2,
                'location' => 'Lạng Sơn',
                'start_date' => '2026-11-10',
                'end_date' => '2026-11-11',
                'slots' => 25,
                'available_slots' => 18,
                'image' => 'tours/ban-gioc.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Bắc Kạn - Hồ Ba Bể',
                'description' => 'Thư giãn bên hồ nước ngọt tự nhiên trên núi lớn nhất Việt Nam.',
                'price' => 1950000,
                'duration' => 2,
                'location' => 'Bắc Kạn',
                'start_date' => '2026-11-15',
                'end_date' => '2026-11-16',
                'slots' => 22,
                'available_slots' => 22,
                'image' => 'tours/yenbai.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Hà Nội - Khám Phá 36 Phố Phường',
                'description' => 'Tìm hiểu nét văn hóa cổ kính ẩm thực ngõ ngách thủ đô nghìn năm văn hiến.',
                'price' => 950000,
                'duration' => 1,
                'location' => 'Hà Nội',
                'start_date' => '2026-11-20',
                'end_date' => '2026-11-20',
                'slots' => 30,
                'available_slots' => 30,
                'image' => 'tours/ha-long.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Bà Nà Hills - Đường Lên Tiên Cảnh',
                'description' => 'Check-in Cầu Vàng nổi tiếng thế giới và khu làng Pháp lãng mạn trên đỉnh núi.',
                'price' => 1550000,
                'duration' => 1,
                'location' => 'Đà Nẵng',
                'start_date' => '2026-11-25',
                'end_date' => '2026-11-25',
                'slots' => 50,
                'available_slots' => 42,
                'image' => 'tours/da-nang.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Bến Tre - Miệt Vườn Trái Cây',
                'description' => 'Thưởng thức trái cây ngọt lành ngay tại vườn và chèo xuồng ba lá lạch dừa.',
                'price' => 1100000,
                'duration' => 1,
                'location' => 'Bến Tre',
                'start_date' => '2026-12-01',
                'end_date' => '2026-12-01',
                'slots' => 35,
                'available_slots' => 33,
                'image' => 'tours/mekong.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Sapa - Săn Mây Đỉnh O Quy Hồ',
                'description' => 'Ngắm cảnh mây trời cuồn cuộn đổ vách núi tại con đèo hùng vĩ nhất miền Bắc.',
                'price' => 2150000,
                'duration' => 2,
                'location' => 'Lào Cai',
                'start_date' => '2026-12-05',
                'end_date' => '2026-12-06',
                'slots' => 20,
                'available_slots' => 0,
                'image' => 'tours/sapa.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Đảo Điệp Sơn - Con Đường Dưới Biển',
                'description' => 'Trải nghiệm đi bộ độc đáo trên con đường cát xuyên biển độc nhất vô nhị.',
                'price' => 1850000,
                'duration' => 2,
                'location' => 'Khánh Hòa',
                'start_date' => '2026-12-10',
                'end_date' => '2026-12-11',
                'slots' => 30,
                'available_slots' => 28,
                'image' => 'tours/nha-trang.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Đà Lạt - Săn Mây Trại Mát',
                'description' => 'Thức dậy từ sớm đón bình minh lên giữa biển sương mù bồng bềnh cao nguyên.',
                'price' => 1600000,
                'duration' => 2,
                'location' => 'Lâm Đồng',
                'start_date' => '2026-12-15',
                'end_date' => '2026-12-16',
                'slots' => 30,
                'available_slots' => 30,
                'image' => 'tours/da-lat.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Phú Quốc - Ngắm Hoàng Hôn Sunset Sanato',
                'description' => 'Check-in địa điểm ngắm hoàng hôn buông xuống biển đẹp lãng mạn bậc nhất.',
                'price' => 2900000,
                'duration' => 3,
                'location' => 'Kiên Giang',
                'start_date' => '2026-12-20',
                'end_date' => '2026-12-22',
                'slots' => 25,
                'available_slots' => 15,
                'image' => 'tours/phu-quoc.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Cố Đô Huế - Ca Trù Sông Hương',
                'description' => 'Thưởng thức nhã nhạc cung đình và thả đèn hoa đăng trên dòng sông Hương thơ mộng.',
                'price' => 1350000,
                'duration' => 2,
                'location' => 'Huế',
                'start_date' => '2026-12-25',
                'end_date' => '2026-12-26',
                'slots' => 20,
                'available_slots' => 20,
                'image' => 'tours/hue.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Hải Phòng - Đảo Hòn Dấu',
                'description' => 'Khám phá ngọn hải đăng cổ kính và đảo hoang sơ vùng đất cảng.',
                'price' => 1250000,
                'duration' => 2,
                'location' => 'Hải Phòng',
                'start_date' => '2027-01-01',
                'end_date' => '2027-01-02',
                'slots' => 30,
                'available_slots' => 24,
                'image' => 'tours/cat-ba.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Hoàng Su Phì - Ruộng Bậc Thang Mùa Nước Đổ',
                'description' => 'Ngắm nhìn những ô ruộng lấp lánh như chiếc gương khổng lồ giữa núi rừng.',
                'price' => 3100000,
                'duration' => 4,
                'location' => 'Hà Giang',
                'start_date' => '2027-01-05',
                'end_date' => '2027-01-08',
                'slots' => 15,
                'available_slots' => 8,
                'image' => 'tours/ha-giang.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Cù Lao Chàm - Lặn Biển San Hô',
                'description' => 'Tận hưởng bầu không khí trong lành biển đảo và lặn ngắm san hô tự nhiên.',
                'price' => 1650000,
                'duration' => 2,
                'location' => 'Quảng Nam',
                'start_date' => '2027-01-10',
                'end_date' => '2027-01-11',
                'slots' => 32,
                'available_slots' => 0,
                'image' => 'tours/son-tra.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Côn Đảo - Viếng Nghĩa Trang Hàng Dương',
                'description' => 'Hành trình lịch sử tâm linh tri ân các anh hùng liệt sĩ vùng đất thiêng.',
                'price' => 3400000,
                'duration' => 3,
                'location' => 'Côn Đảo',
                'start_date' => '2027-01-15',
                'end_date' => '2027-01-17',
                'slots' => 18,
                'available_slots' => 0,
                'image' => 'tours/con-dao.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Yên Tử - Đất Tổ Phật Giáo',
                'description' => 'Hành hương về vùng đất thiêng Yên Tử cầu bình an may mắn đầu năm.',
                'price' => 1350000,
                'duration' => 1,
                'location' => 'Quảng Ninh',
                'start_date' => '2027-01-20',
                'end_date' => '2027-01-20',
                'slots' => 40,
                'available_slots' => 12,
                'image' => 'tours/van-ha.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Thung Lũng Mai Châu - Đêm Nhạc Bản Lác',
                'description' => 'Hòa mình cùng điệu múa xòe hoa uống rượu cần ấm áp vùng thung lũng xanh.',
                'price' => 1850000,
                'duration' => 2,
                'location' => 'Hòa Bình',
                'start_date' => '2027-01-25',
                'end_date' => '2027-01-26',
                'slots' => 26,
                'available_slots' => 5,
                'image' => 'tours/mai-chau.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Hồ Thác Bà - Khám Phá Thủy Điện',
                'description' => 'Du thuyền trên hồ nhân tạo ngắm nhìn các hòn đảo lớn nhỏ xanh tươi.',
                'price' => 1900000,
                'duration' => 2,
                'location' => 'Yên Bái',
                'start_date' => '2027-02-01',
                'end_date' => '2027-02-02',
                'slots' => 24,
                'available_slots' => 8,
                'image' => 'tours/ba-be.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Tuyệt Tình Cốc Ninh Bình',
                'description' => 'Ngắm tiên cảnh hồ nước xanh ngọc bích nằm ẩn mình giữa lòng núi đá vôi.',
                'price' => 1500000,
                'duration' => 2,
                'location' => 'Ninh Bình',
                'start_date' => '2027-02-05',
                'end_date' => '2027-02-06',
                'slots' => 28,
                'available_slots' => 19,
                'image' => 'tours/ninh-binh.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Đảo Bình Ba - Vương Quốc Tôm Hùm',
                'description' => 'Thưởng thức hải sản tươi ngon đặc sản biển đảo Cam Ranh thơ mộng.',
                'price' => 2250000,
                'duration' => 2,
                'location' => 'Khánh Hòa',
                'start_date' => '2027-02-10',
                'end_date' => '2027-02-11',
                'slots' => 32,
                'available_slots' => 16,
                'image' => 'tours/ha-giang-2.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Đồng Hới - Bãi Biển Nhật Lệ',
                'description' => 'Tự do tắm biển ngắm cảnh thành phố thanh bình bên dòng sông Nhật Lệ.',
                'price' => 1650000,
                'duration' => 2,
                'location' => 'Quảng Bình',
                'start_date' => '2027-02-15',
                'end_date' => '2027-02-16',
                'slots' => 20,
                'available_slots' => 20,
                'image' => 'tours/phong-nha.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Cao Bằng - Suối Lênin',
                'description' => 'Thăm di tích lịch sử Pác Bó dòng suối xanh trong vắt dịu mát tâm hồn.',
                'price' => 2100000,
                'duration' => 3,
                'location' => 'Cao Bằng',
                'start_date' => '2027-02-20',
                'end_date' => '2027-02-22',
                'slots' => 18,
                'available_slots' => 9,
                'image' => 'tours/ban-gioc.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Sapa - Check-in Bản Cát Cát',
                'description' => 'Khám phá ngôi làng cổ đẹp nhất Tây Bắc tìm hiểu cuộc sống đồng bào Mông.',
                'price' => 2450000,
                'duration' => 3,
                'location' => 'Lào Cai',
                'start_date' => '2027-02-25',
                'end_date' => '2027-02-27',
                'slots' => 16,
                'available_slots' => 16,
                'image' => 'tours/yenbai.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Chùa Hương - Trẩy Hội Nam Thiên Đệ Nhất Động',
                'description' => 'Ngồi thuyền xuôi dòng suối Yến vãn cảnh quần thể tâm linh linh thiêng.',
                'price' => 990000,
                'duration' => 1,
                'location' => 'Hà Nội',
                'start_date' => '2027-03-01',
                'end_date' => '2027-03-01',
                'slots' => 40,
                'available_slots' => 40,
                'image' => 'tours/ha-long.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Huế - Đà Nẵng - Hội An Hành Trình Di Sản',
                'description' => 'Chuyến đi xuyên qua những địa danh văn hóa lịch sử nổi tiếng miền Trung.',
                'price' => 3500000,
                'duration' => 4,
                'location' => 'Miền Trung',
                'start_date' => '2027-03-05',
                'end_date' => '2027-03-08',
                'slots' => 30,
                'available_slots' => 22,
                'image' => 'tours/da-nang.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Châu Đốc - Miếu Bà Chúa Xứ',
                'description' => 'Hành trình tâm linh miền Tây cầu tài lộc may mắn bình an cho gia đình.',
                'price' => 1400000,
                'duration' => 2,
                'location' => 'An Giang',
                'start_date' => '2027-03-10',
                'end_date' => '2027-03-12',
                'slots' => 35,
                'available_slots' => 30,
                'image' => 'tours/mekong.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Lai Châu - Chinh Phục Đỉnh Pu Si Lung',
                'description' => 'Thử thách bản thân trekking qua cánh rừng già biên giới đại ngàn hùng vĩ.',
                'price' => 3900000,
                'duration' => 4,
                'location' => 'Lai Châu',
                'start_date' => '2027-03-15',
                'end_date' => '2027-03-18',
                'slots' => 15,
                'available_slots' => 0,
                'image' => 'tours/sapa.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Bình Hưng - Đảo Ngọc Hoang Sơ',
                'description' => 'Thư giãn yên bình tại bãi biển trong vắt nước nông nhìn tận đáy hải sản tươi ngon.',
                'price' => 1750000,
                'duration' => 2,
                'location' => 'Khánh Hòa',
                'start_date' => '2027-03-20',
                'end_date' => '2027-03-21',
                'slots' => 30,
                'available_slots' => 25,
                'image' => 'tours/nha-trang.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Đà Lạt - Vườn Hoa Cẩm Tú Cầu',
                'description' => 'Lạc bước check-in giữa cánh đồng hoa cẩm tú cầu nở rộ rực rỡ cả góc trời.',
                'price' => 1550000,
                'duration' => 2,
                'location' => 'Lâm Đồng',
                'start_date' => '2027-03-25',
                'end_date' => '2027-03-26',
                'slots' => 30,
                'available_slots' => 30,
                'image' => 'tours/da-lat.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Rạch Giá - Đảo Hòn Sơn',
                'description' => 'Tận hưởng kỳ nghỉ hoang sơ tuyệt vời rặng dừa xanh nghiêng bóng mát.',
                'price' => 2500000,
                'duration' => 3,
                'location' => 'Kiên Giang',
                'start_date' => '2027-04-01',
                'end_date' => '2027-04-03',
                'slots' => 28,
                'available_slots' => 18,
                'image' => 'tours/phu-quoc.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Huế - Lăng Khải Định Cổ Kính',
                'description' => 'Chiêm ngưỡng đỉnh cao nghệ thuật khảm sành sứ độc đáo triều Nguyễn.',
                'price' => 1200000,
                'duration' => 2,
                'location' => 'Huế',
                'start_date' => '2027-04-05',
                'end_date' => '2027-04-06',
                'slots' => 25,
                'available_slots' => 25,
                'image' => 'tours/hue.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Vân Đồn - Quan Lạn Biển Gọi',
                'description' => 'Khám phá bãi tắm Minh Châu cát trắng mịn màng nước biển mát lành trong xanh.',
                'price' => 2200000,
                'duration' => 3,
                'location' => 'Quảng Ninh',
                'start_date' => '2027-04-10',
                'end_date' => '2027-04-12',
                'slots' => 22,
                'available_slots' => 12,
                'image' => 'tours/cat-ba.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Hà Giang - Mùa Hoa Tam Giác Mạch',
                'description' => 'Đắm chìm không gian sắc hồng mộng mơ phủ kín các thung lũng đá tai mèo.',
                'price' => 3400000,
                'duration' => 4,
                'location' => 'Hà Giang',
                'start_date' => '2027-04-15',
                'end_date' => '2027-04-18',
                'slots' => 15,
                'available_slots' => 11,
                'image' => 'tours/ha-giang.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Ngũ Hành Sơn - Chùa Linh Ứng',
                'description' => 'Hành trình tâm linh khám phá hệ thống hang động thạch nhũ huyền bí.',
                'price' => 1450000,
                'duration' => 2,
                'location' => 'Đà Nẵng',
                'start_date' => '2027-04-20',
                'end_date' => '2027-04-21',
                'slots' => 32,
                'available_slots' => 0,
                'image' => 'tours/son-tra.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Côn Đảo - Câu Cá Biển Đông',
                'description' => 'Trải nghiệm lênh đênh mặt biển thử thách kỹ năng câu cá đại dương.',
                'price' => 3500000,
                'duration' => 3,
                'location' => 'Côn Đảo',
                'start_date' => '2027-04-25',
                'end_date' => '2027-04-27',
                'slots' => 18,
                'available_slots' => 0,
                'image' => 'tours/con-dao.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Móng Cái - Cửa Khẩu Quốc Tế',
                'description' => 'Ghé thăm thành phố biên mậu sầm uất mua sắm giao thương đặc sắc.',
                'price' => 1600000,
                'duration' => 2,
                'location' => 'Quảng Ninh',
                'start_date' => '2027-05-01',
                'end_date' => '2027-05-02',
                'slots' => 35,
                'available_slots' => 15,
                'image' => 'tours/van-ha.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Cao Nguyên Mộc Châu - Đồi Chè Trái Tim',
                'description' => 'Chụp ảnh đồi chè xanh mướt trải dài bao la ngút ngàn hút tầm mắt.',
                'price' => 1750000,
                'duration' => 2,
                'location' => 'Sơn La',
                'start_date' => '2027-05-05',
                'end_date' => '2027-05-06',
                'slots' => 26,
                'available_slots' => 4,
                'image' => 'tours/mai-chau.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Tuyên Quang - Suối Khoáng Nóng Mỹ Lâm',
                'description' => 'Tận hưởng cảm giác thư giãn ngâm mình dòng khoáng nóng tự nhiên tốt cho sức khỏe.',
                'price' => 1850000,
                'duration' => 2,
                'location' => 'Tuyên Quang',
                'start_date' => '2027-05-10',
                'end_date' => '2027-05-12',
                'slots' => 24,
                'available_slots' => 3,
                'image' => 'tours/ba-be.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Ninh Bình - Cố Đô Hoa Lư',
                'description' => 'Ngược dòng lịch sử tìm hiểu kinh đô đầu tiên nhà nước phong kiến tập quyền.',
                'price' => 1350000,
                'duration' => 2,
                'location' => 'Ninh Bình',
                'start_date' => '2027-05-15',
                'end_date' => '2027-05-16',
                'slots' => 28,
                'available_slots' => 10,
                'image' => 'tours/ninh-binh.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Nha Trang - Đảo Khỉ Hòn Lao',
                'description' => 'Vui chơi cùng bầy khỉ hoang dã tinh nghịch tự nhiên thân thiện.',
                'price' => 1400000,
                'duration' => 2,
                'location' => 'Khánh Hòa',
                'start_date' => '2027-05-20',
                'end_date' => '2027-05-21',
                'slots' => 32,
                'available_slots' => 12,
                'image' => 'tours/ha-giang-2.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Quảng Bình - Suối Nước Moọc',
                'description' => 'Trải nghiệm chèo thuyền kayak tắm suối xanh mát giữa núi rừng hoang sơ.',
                'price' => 1900000,
                'duration' => 2,
                'location' => 'Quảng Bình',
                'start_date' => '2027-05-25',
                'end_date' => '2027-05-26',
                'slots' => 20,
                'available_slots' => 20,
                'image' => 'tours/phong-nha.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Lạng Sơn - Đền Mẫu Đồng Đăng',
                'description' => 'Hành trình chiêm bái di tích kiến trúc lịch sử tâm linh vùng biên giới.',
                'price' => 1500000,
                'duration' => 2,
                'location' => 'Lạng Sơn',
                'start_date' => '2027-06-01',
                'end_date' => '2027-06-02',
                'slots' => 18,
                'available_slots' => 5,
                'image' => 'tours/ban-gioc.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Điện Biên - Chiến Trường Xưa Oai Hùng',
                'description' => 'Thăm lại hầm Đờ Cát đồi A1 vang dội cột mốc lịch sử hào hùng dân tộc.',
                'price' => 2950000,
                'duration' => 3,
                'location' => 'Điện Biên',
                'start_date' => '2027-06-05',
                'end_date' => '2027-06-07',
                'slots' => 16,
                'available_slots' => 16,
                'image' => 'tours/yenbai.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Hà Nội - Làng Cổ Đường Lâm',
                'description' => 'Trở về không gian xưa mái ngói cây đa bến nước sân đình mộc mạc.',
                'price' => 850000,
                'duration' => 1,
                'location' => 'Hà Nội',
                'start_date' => '2027-06-10',
                'end_date' => '2027-06-10',
                'slots' => 30,
                'available_slots' => 30,
                'image' => 'tours/ha-long.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Đà Nẵng - Bán Đảo Sơn Trà Chùa Linh Ứng',
                'description' => 'Chiêm ngưỡng tượng Phật Bà Quan Âm cao nhất Việt Nam hướng nhìn ra biển.',
                'price' => 1250000,
                'duration' => 2,
                'location' => 'Đà Nẵng',
                'start_date' => '2027-06-15',
                'end_date' => '2027-06-16',
                'slots' => 25,
                'available_slots' => 25,
                'image' => 'tours/da-nang.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Đồng Tháp - Vườn Quốc Gia Tràm Chim',
                'description' => 'Khám phá hệ sinh thái đất ngập nước ngắm sếu đầu đỏ quý hiếm.',
                'price' => 1750000,
                'duration' => 2,
                'location' => 'Đồng Tháp',
                'start_date' => '2027-06-20',
                'end_date' => '2027-06-22',
                'slots' => 35,
                'available_slots' => 31,
                'image' => 'tours/mekong.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Sa Pa - Cáp Treo Fansipan Legend',
                'description' => 'Hành trình vượt mây bằng cáp treo hiện đại chinh phục nóc nhà Đông Dương.',
                'price' => 2800000,
                'duration' => 3,
                'location' => 'Lào Cai',
                'start_date' => '2027-06-25',
                'end_date' => '2027-06-28',
                'slots' => 20,
                'available_slots' => 0,
                'image' => 'tours/sapa.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Nha Trang - Suối Hoa Lan',
                'description' => 'Khám phá thiên nhiên rực rỡ sắc màu phong lan ven vịnh Nha Phu.',
                'price' => 1450000,
                'duration' => 2,
                'location' => 'Khánh Hòa',
                'start_date' => '2027-07-01',
                'end_date' => '2027-07-02',
                'slots' => 40,
                'available_slots' => 40,
                'image' => 'tours/nha-trang.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Đà Lạt - Thung Lũng Tình Yêu',
                'description' => 'Thăm điểm đến lãng mạn thơ mộng biểu tượng tình yêu đôi lứa phố hoa.',
                'price' => 1650000,
                'duration' => 2,
                'location' => 'Lâm Đồng',
                'start_date' => '2027-07-05',
                'end_date' => '2027-07-06',
                'slots' => 30,
                'available_slots' => 30,
                'image' => 'tours/da-lat.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Phú Quốc - Khám Phá Hòn Thơm',
                'description' => 'Trải nghiệm cáp treo vượt biển dài nhất thế giới vui chơi công viên nước.',
                'price' => 2750000,
                'duration' => 3,
                'location' => 'Kiên Giang',
                'start_date' => '2027-07-10',
                'end_date' => '2027-07-12',
                'slots' => 28,
                'available_slots' => 9,
                'image' => 'tours/phu-quoc.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Huế - Chùa Thiên Mụ Cổ Kính',
                'description' => 'Ghé thăm ngôi chùa cổ linh thiêng soi bóng bên dòng sông Hương hiền hòa.',
                'price' => 1100000,
                'duration' => 2,
                'location' => 'Huế',
                'start_date' => '2027-07-15',
                'end_date' => '2027-07-16',
                'slots' => 25,
                'available_slots' => 25,
                'image' => 'tours/hue.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Đảo Cát Bà - Vịnh Lan Hạ Khám Phá',
                'description' => 'Chèo kayak luồn lách qua các hang sáng hang tối ngắm cảnh hoang sơ.',
                'price' => 2050000,
                'duration' => 3,
                'location' => 'Hải Phòng',
                'start_date' => '2027-07-20',
                'end_date' => '2027-07-22',
                'slots' => 22,
                'available_slots' => 6,
                'image' => 'tours/cat-ba.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Hà Giang - Chinh Phục Cột Cờ Lũng Cú',
                'description' => 'Niềm tự hào đứng dưới lá cờ Tổ quốc thiêng liêng nơi địa đầu đất nước.',
                'price' => 3300000,
                'duration' => 4,
                'location' => 'Hà Giang',
                'start_date' => '2027-07-25',
                'end_date' => '2027-07-28',
                'slots' => 15,
                'available_slots' => 4,
                'image' => 'tours/ha-giang.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Đèo Hải Vân - Thiên Hạ Đệ Nhất Hùng Quan',
                'description' => 'Trải nghiệm những cung đường đèo uốn lượn ngắm nhìn đại dương bao la.',
                'price' => 1500000,
                'duration' => 2,
                'location' => 'Miền Trung',
                'start_date' => '2027-08-01',
                'end_date' => '2027-08-02',
                'slots' => 32,
                'available_slots' => 0,
                'image' => 'tours/son-tra.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Bãi Đầm Trầu Côn Đảo',
                'description' => 'Tắm biển thư giãn ngắm máy bay cất cánh hạ cánh sát ngay trên bãi biển.',
                'price' => 3100000,
                'duration' => 3,
                'location' => 'Côn Đảo',
                'start_date' => '2027-08-05',
                'end_date' => '2027-08-07',
                'slots' => 18,
                'available_slots' => 0,
                'image' => 'tours/con-dao.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Vịnh Hạ Long - Động Thiên Cung',
                'description' => 'Chiêm ngưỡng mê cung thạch nhũ lộng lẫy tráng lệ bậc nhất vịnh di sản.',
                'price' => 1400000,
                'duration' => 1,
                'location' => 'Quảng Ninh',
                'start_date' => '2027-08-10',
                'end_date' => '2027-08-10',
                'slots' => 35,
                'available_slots' => 1,
                'image' => 'tours/van-ha.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Bản Lác Mai Châu Hòa Bình',
                'description' => 'Tìm hiểu đời sống mộc mạc phong tục tập quán lâu đời người đồng bào Thái.',
                'price' => 1700000,
                'duration' => 2,
                'location' => 'Hòa Bình',
                'start_date' => '2027-08-15',
                'end_date' => '2027-08-16',
                'slots' => 26,
                'available_slots' => 1,
                'image' => 'tours/mai-chau.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Na Hang Tuyên Quang',
                'description' => 'Du ngoạn lòng hồ sinh thái Na Hang ngắm núi non trùng điệp kỳ vĩ.',
                'price' => 1950000,
                'duration' => 2,
                'location' => 'Tuyên Quang',
                'start_date' => '2027-08-20',
                'end_date' => '2027-08-22',
                'slots' => 24,
                'available_slots' => 2,
                'image' => 'tours/ba-be.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Khu Sinh Thái Tràng An Ninh Bình',
                'description' => 'Ngồi thuyền xuyên qua các hang động ngập nước ngắm cảnh phim Đảo Đầu Lâu.',
                'price' => 1600000,
                'duration' => 2,
                'location' => 'Ninh Bình',
                'start_date' => '2027-08-25',
                'end_date' => '2027-08-26',
                'slots' => 28,
                'available_slots' => 11,
                'image' => 'tours/ninh-binh.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Đảo Hòn Mun Nha Trang',
                'description' => 'Tận hưởng thiên đường lặn biển ngắm các loài san hô quý hiếm đa sắc màu.',
                'price' => 2100000,
                'duration' => 3,
                'location' => 'Khánh Hòa',
                'start_date' => '2027-09-01',
                'end_date' => '2027-09-03',
                'slots' => 32,
                'available_slots' => 14,
                'image' => 'tours/ha-giang-2.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Động Thiên Đường Quảng Bình',
                'description' => 'Khám phá hoàng cung trong lòng đất kiến trúc thạch nhũ dài kỷ lục.',
                'price' => 1800000,
                'duration' => 2,
                'location' => 'Quảng Bình',
                'start_date' => '2027-09-05',
                'end_date' => '2027-09-06',
                'slots' => 20,
                'available_slots' => 20,
                'image' => 'tours/phong-nha.jpg',
                'status' => 'inactive',
            ],
            [
                'title' => 'Tour Thác Bản Giốc Cao Bằng Hùng Vĩ',
                'description' => 'Ngắm dòng thác ba tầng tuôn đổ bọt tung trắng xóa biên cương Tổ quốc.',
                'price' => 1600000,
                'duration' => 2,
                'location' => 'Cao Bằng',
                'start_date' => '2027-09-10',
                'end_date' => '2027-09-11',
                'slots' => 18,
                'available_slots' => 8,
                'image' => 'tours/ban-gioc.jpg',
                'status' => 'active',
            ],
            [
                'title' => 'Tour Sapa Trekking Bản Tả Van',
                'description' => 'Băng qua thung lũng Mường Hoa thơ mộng tìm hiểu bản sắc người Giáy.',
                'price' => 2550000,
                'duration' => 3,
                'location' => 'Lào Cai',
                'start_date' => '2027-09-15',
                'end_date' => '2027-09-17',
                'slots' => 16,
                'available_slots' => 16,
                'image' => 'tours/yenbai.jpg',
                'status' => 'inactive',
            ],
        ];

        foreach ($tours as $tour) {
            Tour::create($tour);
        }
    }
}
